Add variables to enable join based on bootstrap token

diff --git a/modules/install-k8s/kubeadm-init b/modules/install-k8s/kubeadm-init
--- a/modules/install-k8s/kubeadm-init
+++ b/modules/install-k8s/kubeadm-init
@@ -19,9 +19,21 @@ export ETCDCTL_API=3
 ETCDCTL_COMMAND="/opt/k8s/bin/etcdctl --cacert $ETCD_CA_FILE --cert $ETCD_CERT_FILE --key $ETCD_KEY_FILE --endpoints $ETCD_ENDPOINTS"
 
 # Try to get pki from etcd, if already generated by a previous run of kubeadm
-PKI=$($ETCDCTL_COMMAND get --print-value-only "$PKI_ETCD_KEY")
-TOKEN=$($ETCDCTL_COMMAND get --print-value-only $BOOTSTRAP_TOKEN_ETCD_KEY)
-CACRT_SHASUM=$($ETCDCTL_COMMAND get --print-value-only $CACRT_SHASUM_ETCD_KEY)
+if [ "$MASTER_MODE" == "1" ] && [ ! -z "$ETCD_ENDPOINTS" ]; then
+    PKI=$($ETCDCTL_COMMAND get --print-value-only "$PKI_ETCD_KEY")
+fi
+
+if [ -z "$BOOTSTRAP_TOKEN" ]; then
+    TOKEN=$($ETCDCTL_COMMAND get --print-value-only $BOOTSTRAP_TOKEN_ETCD_KEY)
+else
+    TOKEN="$BOOTSTRAP_TOKEN"
+fi
+
+if [ -z "$CACRT_SHA256SUM" ]; then
+    CACRT_SHA256SUM=$($ETCDCTL_COMMAND get --print-value-only $CACRT_SHA256SUM_ETCD_KEY)
+else
+    CACRT_SHA256SUM="$CACRT_SHA256SUM"
+fi
 
 if [ -z "$API_ENDPOINT" ]; then
     JOIN=$($ETCDCTL_COMMAND get --prefix "$MASTERS_ETCD_KEYPREFIX" --print-value-only --limit 1):6443
@@ -29,14 +41,20 @@ else
     JOIN="$API_ENDPOINT"
 fi
 
-if [ -z "$PKI" ] || [ -z "$TOKEN" ] || [ -z "$CACRT_SHASUM" ]; then
-    etcd_keys=missing
+if [ -z "$PKI" ] || [ -z "$TOKEN" ] || [ -z "$CACRT_SHA256SUM" ]; then
+    master_keys=missing
 else
-    etcd_keys=present
+    master_keys=present
+fi
+
+if [ -z "$TOKEN" ] || [ -z "$CACRT_SHA256SUM" ]; then
+    worker_keys=missing
+else
+    worker_keys=present
 fi
 
 # Node is a master
-if [ "$MASTER_MODE" == "1" ] && [ "$etcd_keys" == "missing" ]; then
+if [ "$MASTER_MODE" == "1" ] && [ "$master_keys" == "missing" ]; then
     # we need to generate the pki & token and store it into the etcd
 
     echo "primary master. kubeadm init" >&2
@@ -62,10 +80,10 @@ if [ "$MASTER_MODE" == "1" ] && [ "$etcd_keys" == "missing" ]; then
 
     echo "Putting cacrt sha256sum into etcd." >&2
     cacrtsum=$(openssl x509 -in /etc/kubernetes/pki/ca.crt -noout -pubkey | openssl rsa -pubin -outform DER 2>/dev/null | sha256sum | cut -d' ' -f1)
-    $ETCDCTL_COMMAND put "$CACRT_SHASUM_ETCD_KEY" "sha256:$cacrtsum"
+    $ETCDCTL_COMMAND put "$CACRT_SHA256SUM_ETCD_KEY" "sha256:$cacrtsum"
 
     echo "Putting cacrt into etcd." >&2
-    $ETCDCTL_COMMAND put "$CACRT_ETCD_KEY" "$(cat /etc/kubernetes/ca.crt | base64)"
+    $ETCDCTL_COMMAND put "$CACRT_ETCD_KEY" "$(cat /etc/kubernetes/pki/ca.crt | base64)"
 
     echo "Setting admin user credentials in etcd" >&2
     user=${K8S_ADMIN_SA_USERNAME}
@@ -89,40 +107,35 @@ if [ "$MASTER_MODE" == "1" ] && [ "$etcd_keys" == "missing" ]; then
     echo "Putting admin sa endpoint into etcd." >&2
     $ETCDCTL_COMMAND put "$K8S_ADMIN_SA_ENDPOINT_ETCD_KEY" "${endpoint}"
 
+elif [ "$MASTER_MODE" == "1" ] && [ "$master_keys" == "present" ]; then
+    echo "pki already in etcd. retrieving.." >&2
+    mkdir -p /etc/kubernetes/pki
+    (cd /etc/kubernetes/pki  && echo -e "$PKI" | base64 -d | tar -xf -)
 
-elif  [ "$etcd_keys" == "present" ]; then
-    if [ "$MASTER_MODE" == "1" ]; then
-        echo "pki already in etcd. retrieving.." >&2
-        mkdir -p /etc/kubernetes/pki
-        (cd /etc/kubernetes/pki  && echo -e "$PKI" | base64 -d | tar -xf -)
-
-        # Join the cluster
-        echo "Joining the cluster as master on endpoint $API_ENDPOINT" >&2
-        /opt/k8s/bin/kubeadm join \
-                             --discovery-token-ca-cert-hash "$CACRT_SHASUM" \
-                             --token "$TOKEN" \
-                             --experimental-control-plane \
-                             "$JOIN"
-        echo "Registering master into etcd." >&2
-        if ip=$(pubipaddr); then
-            $ETCDCTL_COMMAND put "${MASTERS_ETCD_KEYPREFIX}/$(hostname)" "$ip"
-        else
-            echo "WARNING: Couldn't get ip addr & register master node." >&2
-        fi
-    elif [ "$WORKER_MODE" == "1" ]; then
-        echo "Joining the cluster as worker on endpoint $API_ENDPOINT" >&2
-        /opt/k8s/bin/kubeadm join \
-                             --discovery-token-ca-cert-hash "$CACRT_SHASUM" \
-                             --token "$TOKEN" \
-                             "$JOIN"
+    # Join the cluster
+    echo "Joining the cluster as master on endpoint $API_ENDPOINT" >&2
+    /opt/k8s/bin/kubeadm join \
+                         --discovery-token-ca-cert-hash "$CACRT_SHA256SUM" \
+                         --token "$TOKEN" \
+                         --experimental-control-plane \
+                         "$JOIN"
+    echo "Registering master into etcd." >&2
+    if ip=$(pubipaddr); then
+        $ETCDCTL_COMMAND put "${MASTERS_ETCD_KEYPREFIX}/$(hostname)" "$ip"
     else
-        echo "Neither worker nor master" >&2
+        echo "WARNING: Couldn't get ip addr & register master node." >&2
     fi
+elif [ "$WORKER_MODE" == "1" ] && [ "$worker_keys" == "present" ]; then
+    echo "Joining the cluster as worker on endpoint $API_ENDPOINT" >&2
+    /opt/k8s/bin/kubeadm join \
+                         --discovery-token-ca-cert-hash "$CACRT_SHA256SUM" \
+                         --token "$TOKEN" \
+                         "$JOIN"
 else
     if [ -z "$TOKEN" ]; then
         echo "No bootstrap token found into etcd" >&2
     fi
-    if [ -z "$CACRT_SHASUM" ]; then
+    if [ -z "$CACRT_SHA256SUM" ]; then
         echo "No cacrt found into etcd" >&2
     fi
     if [ -z "$PKI" ]; then
