Refactor k8s-init systemd service

diff --git a/modules/install-k8s/kubeadm-init b/modules/install-k8s/kubeadm-init
--- a/modules/install-k8s/kubeadm-init
+++ b/modules/install-k8s/kubeadm-init
@@ -1,158 +1,84 @@
-#!/bin/bash -e
-if [ "$MASTER_MODE" == "0" ] && [ "$WORKER_MODE" == "0" ]; then
+#!/bin/bash
+
+# kubeadm-init runs kubeadm init/join on masters or workers
+# its based on tokens/pkis either given as env vars or registered in ETCD
+
+set -eo pipefail
+
+if [ "$MASTER_MODE" != "1" ] && [ "$WORKER_MODE" != "1" ]; then
     echo "nothing to be done" >&2
+    exit 0
 fi
 
-function pubipaddr(){
-    if ip route get 1.1.1.1 > /dev/null 2>&1; then
-        ip -o route get 1.1.1.1 | sed 's/.*src \([0-9\.]*\) .*/\1/g'
-    else
-        return 1
-    fi
-}
+# Do not run if init has already been done
+if [ -f /opt/k8s/kubeadm-init.done ]; then
+    echo "init already done." >&2
+    exit 0
+fi
+
+echo "Ensures kubelet is not running as it will be restarted by kubeadm" >&2
+systemctl stop kubelet
 
 # required as kubeadm will make use of binaries such as kubelet
 export PATH=$PATH:/opt/k8s/bin
+
+echo "Cleanup kubeadm files from a previous init" >&2
+for i in "${POD_MANIFEST_PATH}" \
+             /etc/kubernetes/kubelet.conf \
+             /etc/kubernetes/bootstrap-kubelet.conf; do
+    if [ -f "$i" ] || [ -d "$i" ]; then
+        mv -v -- "${i}" "${i}.bak"
+    fi
+done
+
+# Create manifests path
+if [ ! -d "${POD_MANIFEST_PATH}" ]; then
+    mkdir -p "${POD_MANIFEST_PATH}"
+fi
 
 # Prepare etcdctl command
 export ETCDCTL_API=3
 ETCDCTL_COMMAND="/opt/k8s/bin/etcdctl --cacert $ETCD_CA_FILE --cert $ETCD_CERT_FILE --key $ETCD_KEY_FILE --endpoints $ETCD_ENDPOINTS"
 
-# Try to get pki from etcd, if already generated by a previous run of kubeadm
-if [ "$MASTER_MODE" == "1" ] && [ ! -z "$ETCD_ENDPOINTS" ]; then
-    PKI=$($ETCDCTL_COMMAND get --print-value-only "$PKI_ETCD_KEY")
-fi
-
-if [ -z "$BOOTSTRAP_TOKEN" ]; then
-    TOKEN=$($ETCDCTL_COMMAND get --print-value-only $BOOTSTRAP_TOKEN_ETCD_KEY)
-else
-    TOKEN="$BOOTSTRAP_TOKEN"
-fi
-
-if [ -z "$CACRT_SHA256SUM" ]; then
-    CACRT_SHA256SUM=$($ETCDCTL_COMMAND get --print-value-only $CACRT_SHA256SUM_ETCD_KEY)
-else
-    CACRT_SHA256SUM="$CACRT_SHA256SUM"
-fi
-
-if [ -z "$API_ENDPOINT" ]; then
-    JOIN=$($ETCDCTL_COMMAND get --prefix "$MASTERS_ETCD_KEYPREFIX" --print-value-only --limit 1):6443
-else
-    JOIN="$API_ENDPOINT"
-fi
-
-if [ -z "$PKI" ] || [ -z "$TOKEN" ] || [ -z "$CACRT_SHA256SUM" ]; then
-    master_keys=missing
-else
-    master_keys=present
-fi
-
-if [ -z "$TOKEN" ] || [ -z "$CACRT_SHA256SUM" ]; then
-    worker_keys=missing
-else
-    worker_keys=present
-fi
-
-# Node is a master
-if [ "$MASTER_MODE" == "1" ] && [ "$master_keys" == "missing" ]; then
-    # we need to generate the pki & token and store it into the etcd
-
-    echo "primary master. kubeadm init" >&2
-    # generate kubeadm config
-    if [ ! -d /etc/kubernetes/kubeadm ]; then
-        mkdir -p /etc/kubernetes/kubeadm
-    fi
-
-    # kubeadm init
-    /opt/k8s/kubeadm_config.yaml.sh "${API_ENDPOINT:-$(pubipaddr):6443}" > /etc/kubernetes/kubeadm/config.yaml
-
-    if ! /opt/k8s/bin/kubeadm init --config=/etc/kubernetes/kubeadm/config.yaml; then
-        echo "primary master kubeadm init failed." >&2
+# Acquire lock on kubeadm-init script if initializing a new master
+# Otherwise, run the script without locking
+if [ "$MASTER_MODE" == "1" ]; then
+    echo "initializing master mode" >&2
+    # run kubeadm on master nodes with a lock as the first node will gen
+    # the cluster pki certs
+    if [ -z "$INIT_ETCD_LOCK" ]; then
+        echo "lock var is undefined. cannot proceed" >&2
         exit 1
     fi
 
-    echo "Putting token into etcd." >&2
-    # tokens are valid 24h. if scaling worker nodes after this delay
-    # dont forget to regenerate a valid token before
-    $ETCDCTL_COMMAND put $BOOTSTRAP_TOKEN_ETCD_KEY "$(/opt/k8s/bin/kubeadm token list | tail -n1 | awk '{print $1}')"
-    echo "Putting pki into etcd." >&2
-    $ETCDCTL_COMMAND put "$PKI_ETCD_KEY" "$(cd /etc/kubernetes/pki && tar -cf - * | base64)"
-
-    echo "Putting cacrt sha256sum into etcd." >&2
-    cacrtsum=$(openssl x509 -in /etc/kubernetes/pki/ca.crt -noout -pubkey | openssl rsa -pubin -outform DER 2>/dev/null | sha256sum | cut -d' ' -f1)
-    $ETCDCTL_COMMAND put "$CACRT_SHA256SUM_ETCD_KEY" "sha256:$cacrtsum"
-
-    echo "Putting cacrt into etcd." >&2
-    $ETCDCTL_COMMAND put "$CACRT_ETCD_KEY" "$(cat /etc/kubernetes/pki/ca.crt | base64)"
-
-    echo "Setting admin user credentials in etcd" >&2
-    user=${K8S_ADMIN_SA_USERNAME}
-    KUBECTL="/opt/bin/kubectl --kubeconfig /etc/kubernetes/admin.conf"
-    $KUBECTL create sa "${user}"
-    secret=$($KUBECTL get sa "${user}" -o json | jq -r '.secrets[].name')
-    user_token=$($KUBECTL get secret "${secret}" -o json | jq -r '.data["token"]' | base64 -d)
-    c=$($KUBECTL config current-context)
-    cluster_name=$($KUBECTL config get-contexts $c | awk '{print $3}' | tail -n 1)
-    endpoint=$($KUBECTL config view -o jsonpath="{.clusters[?(@.name == \"${cluster_name}\")].cluster.server}")
-
-    echo "Grant cluster admin role to ${user}" >&2
-    $KUBECTL create clusterrolebinding "${user}-cluster-admin-binding" --clusterrole=cluster-admin --user="system:serviceaccount:default:${user}"
-
-    echo "Putting admin sa username into etcd." >&2
-    $ETCDCTL_COMMAND put "$K8S_ADMIN_SA_USERNAME_ETCD_KEY" "${user}"
-    echo "Putting admin sa token username into etcd." >&2
-    $ETCDCTL_COMMAND put "$K8S_ADMIN_SA_USER_TOKEN_ETCD_KEY" "${user_token}"
-    echo "Putting admin sa cluster name into etcd." >&2
-    $ETCDCTL_COMMAND put "$K8S_ADMIN_SA_CLUSTER_NAME_ETCD_KEY" "${cluster_name}"
-    echo "Putting admin sa endpoint into etcd." >&2
-    $ETCDCTL_COMMAND put "$K8S_ADMIN_SA_ENDPOINT_ETCD_KEY" "${endpoint}"
-
-elif [ "$MASTER_MODE" == "1" ] && [ "$master_keys" == "present" ]; then
-    echo "pki already in etcd. retrieving.." >&2
-    mkdir -p /etc/kubernetes/pki
-    (cd /etc/kubernetes/pki  && echo -e "$PKI" | base64 -d | tar -xf -)
-
-    # Join the cluster
-    echo "Joining the cluster as master on endpoint $API_ENDPOINT" >&2
-    /opt/k8s/bin/kubeadm join \
-                         --discovery-token-ca-cert-hash "$CACRT_SHA256SUM" \
-                         --token "$TOKEN" \
-                         --experimental-control-plane \
-                         "$JOIN"
-    echo "Registering master into etcd." >&2
-    if ip=$(pubipaddr); then
-        $ETCDCTL_COMMAND put "${MASTERS_ETCD_KEYPREFIX}/$(hostname)" "$ip"
-    else
-        echo "WARNING: Couldn't get ip addr & register master node." >&2
-    fi
-elif [ "$WORKER_MODE" == "1" ] && [ "$worker_keys" == "present" ]; then
-    echo "Joining the cluster as worker on endpoint $API_ENDPOINT" >&2
-    /opt/k8s/bin/kubeadm join \
-                         --discovery-token-ca-cert-hash "$CACRT_SHA256SUM" \
-                         --token "$TOKEN" \
-                         "$JOIN"
+    echo "acquiring lock $INIT_ETCD_LOCK" >&2
+    $ETCDCTL_COMMAND lock "$INIT_ETCD_LOCK" /opt/k8s/bin/kubeadm-init-lock
+    echo "kubeadm init done, lock $INIT_ETCD_LOCK released" >&2
 else
-    if [ -z "$TOKEN" ]; then
-        echo "No bootstrap token found into etcd" >&2
-    fi
-    if [ -z "$CACRT_SHA256SUM" ]; then
-        echo "No cacrt found into etcd" >&2
-    fi
-    if [ -z "$PKI" ]; then
-        echo "No pki found into etcd" >&2
-    fi
-    if [ -z "$JOIN" ]; then
-        echo "No master registered or no API_ENDOINT specified found into etcd" >&2
-    fi
-    echo "either etcd hasn't got its keys yet or maybe something went wrong" >&2
-    exit 1
-fi
-
-if [ "$MASTER_MODE" == "1" ]; then
-    echo "Registering master into etcd." >&2
-    if ip=$(pubipaddr); then
-        $ETCDCTL_COMMAND put "${MASTERS_ETCD_KEYPREFIX}/$(hostname)" "$ip"
+    if [ -z "$API_ENDPOINT" ]; then
+        JOIN=$($ETCDCTL_COMMAND get --prefix "$MASTERS_ETCD_KEYPREFIX" \
+                                --print-value-only --limit 1):6443
     else
-        echo "WARNING: Couldn't get ip addr & register master node." >&2
+        JOIN="$API_ENDPOINT"
     fi
+
+    if [ -z "$CACRT_SHA256SUM" ]; then
+        CACRT_SHA256SUM=$($ETCDCTL_COMMAND get \
+                                 --print-value-only "$CACRT_SHA256SUM_ETCD_KEY")
+    else
+        CACRT_SHA256SUM="$CACRT_SHA256SUM"
+    fi
+
+    if [ -z "$BOOTSTRAP_TOKEN" ]; then
+        TOKEN=$($ETCDCTL_COMMAND get \
+                                 --print-value-only "$BOOTSTRAP_TOKEN_ETCD_KEY")
+    else
+        TOKEN="$BOOTSTRAP_TOKEN"
+    fi
+
+    echo "Joining the cluster as worker on endpoint $JOIN" >&2
+    /opt/k8s/bin/kubeadm join \
+                         --discovery-token-ca-cert-hash "$CACRT_SHA256SUM" \
+                         --token "$TOKEN" \
+                         "$JOIN"
 fi
